// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package domain

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.mongodb.org/mongo-driver/v2/bson"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// BatchUpdateIntentsState provides a mock function for the type MockRepository
func (_mock *MockRepository) BatchUpdateIntentsState(ctx context.Context, intentIDs []bson.ObjectID, newState IntentState) error {
	ret := _mock.Called(ctx, intentIDs, newState)

	if len(ret) == 0 {
		panic("no return value specified for BatchUpdateIntentsState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []bson.ObjectID, IntentState) error); ok {
		r0 = returnFunc(ctx, intentIDs, newState)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_BatchUpdateIntentsState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchUpdateIntentsState'
type MockRepository_BatchUpdateIntentsState_Call struct {
	*mock.Call
}

// BatchUpdateIntentsState is a helper method to define mock.On call
//   - ctx context.Context
//   - intentIDs []bson.ObjectID
//   - newState IntentState
func (_e *MockRepository_Expecter) BatchUpdateIntentsState(ctx interface{}, intentIDs interface{}, newState interface{}) *MockRepository_BatchUpdateIntentsState_Call {
	return &MockRepository_BatchUpdateIntentsState_Call{Call: _e.mock.On("BatchUpdateIntentsState", ctx, intentIDs, newState)}
}

func (_c *MockRepository_BatchUpdateIntentsState_Call) Run(run func(ctx context.Context, intentIDs []bson.ObjectID, newState IntentState)) *MockRepository_BatchUpdateIntentsState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []bson.ObjectID
		if args[1] != nil {
			arg1 = args[1].([]bson.ObjectID)
		}
		var arg2 IntentState
		if args[2] != nil {
			arg2 = args[2].(IntentState)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_BatchUpdateIntentsState_Call) Return(err error) *MockRepository_BatchUpdateIntentsState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_BatchUpdateIntentsState_Call) RunAndReturn(run func(ctx context.Context, intentIDs []bson.ObjectID, newState IntentState) error) *MockRepository_BatchUpdateIntentsState_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAuditLog provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateAuditLog(ctx context.Context, log *AuditLog) error {
	ret := _mock.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for CreateAuditLog")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *AuditLog) error); ok {
		r0 = returnFunc(ctx, log)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_CreateAuditLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAuditLog'
type MockRepository_CreateAuditLog_Call struct {
	*mock.Call
}

// CreateAuditLog is a helper method to define mock.On call
//   - ctx context.Context
//   - log *AuditLog
func (_e *MockRepository_Expecter) CreateAuditLog(ctx interface{}, log interface{}) *MockRepository_CreateAuditLog_Call {
	return &MockRepository_CreateAuditLog_Call{Call: _e.mock.On("CreateAuditLog", ctx, log)}
}

func (_c *MockRepository_CreateAuditLog_Call) Run(run func(ctx context.Context, log *AuditLog)) *MockRepository_CreateAuditLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *AuditLog
		if args[1] != nil {
			arg1 = args[1].(*AuditLog)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateAuditLog_Call) Return(err error) *MockRepository_CreateAuditLog_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_CreateAuditLog_Call) RunAndReturn(run func(ctx context.Context, log *AuditLog) error) *MockRepository_CreateAuditLog_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePermission provides a mock function for the type MockRepository
func (_mock *MockRepository) CreatePermission(ctx context.Context, permission *Permission) error {
	ret := _mock.Called(ctx, permission)

	if len(ret) == 0 {
		panic("no return value specified for CreatePermission")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Permission) error); ok {
		r0 = returnFunc(ctx, permission)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_CreatePermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePermission'
type MockRepository_CreatePermission_Call struct {
	*mock.Call
}

// CreatePermission is a helper method to define mock.On call
//   - ctx context.Context
//   - permission *Permission
func (_e *MockRepository_Expecter) CreatePermission(ctx interface{}, permission interface{}) *MockRepository_CreatePermission_Call {
	return &MockRepository_CreatePermission_Call{Call: _e.mock.On("CreatePermission", ctx, permission)}
}

func (_c *MockRepository_CreatePermission_Call) Run(run func(ctx context.Context, permission *Permission)) *MockRepository_CreatePermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Permission
		if args[1] != nil {
			arg1 = args[1].(*Permission)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreatePermission_Call) Return(err error) *MockRepository_CreatePermission_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_CreatePermission_Call) RunAndReturn(run func(ctx context.Context, permission *Permission) error) *MockRepository_CreatePermission_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRole provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateRole(ctx context.Context, role *Role) error {
	ret := _mock.Called(ctx, role)

	if len(ret) == 0 {
		panic("no return value specified for CreateRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Role) error); ok {
		r0 = returnFunc(ctx, role)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_CreateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRole'
type MockRepository_CreateRole_Call struct {
	*mock.Call
}

// CreateRole is a helper method to define mock.On call
//   - ctx context.Context
//   - role *Role
func (_e *MockRepository_Expecter) CreateRole(ctx interface{}, role interface{}) *MockRepository_CreateRole_Call {
	return &MockRepository_CreateRole_Call{Call: _e.mock.On("CreateRole", ctx, role)}
}

func (_c *MockRepository_CreateRole_Call) Run(run func(ctx context.Context, role *Role)) *MockRepository_CreateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Role
		if args[1] != nil {
			arg1 = args[1].(*Role)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateRole_Call) Return(err error) *MockRepository_CreateRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_CreateRole_Call) RunAndReturn(run func(ctx context.Context, role *Role) error) *MockRepository_CreateRole_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateUser(ctx context.Context, user *User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *User
func (_e *MockRepository_Expecter) CreateUser(ctx interface{}, user interface{}) *MockRepository_CreateUser_Call {
	return &MockRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *MockRepository_CreateUser_Call) Run(run func(ctx context.Context, user *User)) *MockRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *User
		if args[1] != nil {
			arg1 = args[1].(*User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateUser_Call) Return(err error) *MockRepository_CreateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_CreateUser_Call) RunAndReturn(run func(ctx context.Context, user *User) error) *MockRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteIntents provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteIntents(ctx context.Context, intentIDs []bson.ObjectID) error {
	ret := _mock.Called(ctx, intentIDs)

	if len(ret) == 0 {
		panic("no return value specified for DeleteIntents")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []bson.ObjectID) error); ok {
		r0 = returnFunc(ctx, intentIDs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeleteIntents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteIntents'
type MockRepository_DeleteIntents_Call struct {
	*mock.Call
}

// DeleteIntents is a helper method to define mock.On call
//   - ctx context.Context
//   - intentIDs []bson.ObjectID
func (_e *MockRepository_Expecter) DeleteIntents(ctx interface{}, intentIDs interface{}) *MockRepository_DeleteIntents_Call {
	return &MockRepository_DeleteIntents_Call{Call: _e.mock.On("DeleteIntents", ctx, intentIDs)}
}

func (_c *MockRepository_DeleteIntents_Call) Run(run func(ctx context.Context, intentIDs []bson.ObjectID)) *MockRepository_DeleteIntents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []bson.ObjectID
		if args[1] != nil {
			arg1 = args[1].([]bson.ObjectID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteIntents_Call) Return(err error) *MockRepository_DeleteIntents_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteIntents_Call) RunAndReturn(run func(ctx context.Context, intentIDs []bson.ObjectID) error) *MockRepository_DeleteIntents_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteIntentsByStrategyID provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteIntentsByStrategyID(ctx context.Context, strategyID bson.ObjectID) error {
	ret := _mock.Called(ctx, strategyID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteIntentsByStrategyID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bson.ObjectID) error); ok {
		r0 = returnFunc(ctx, strategyID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeleteIntentsByStrategyID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteIntentsByStrategyID'
type MockRepository_DeleteIntentsByStrategyID_Call struct {
	*mock.Call
}

// DeleteIntentsByStrategyID is a helper method to define mock.On call
//   - ctx context.Context
//   - strategyID bson.ObjectID
func (_e *MockRepository_Expecter) DeleteIntentsByStrategyID(ctx interface{}, strategyID interface{}) *MockRepository_DeleteIntentsByStrategyID_Call {
	return &MockRepository_DeleteIntentsByStrategyID_Call{Call: _e.mock.On("DeleteIntentsByStrategyID", ctx, strategyID)}
}

func (_c *MockRepository_DeleteIntentsByStrategyID_Call) Run(run func(ctx context.Context, strategyID bson.ObjectID)) *MockRepository_DeleteIntentsByStrategyID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bson.ObjectID
		if args[1] != nil {
			arg1 = args[1].(bson.ObjectID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteIntentsByStrategyID_Call) Return(err error) *MockRepository_DeleteIntentsByStrategyID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteIntentsByStrategyID_Call) RunAndReturn(run func(ctx context.Context, strategyID bson.ObjectID) error) *MockRepository_DeleteIntentsByStrategyID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteStrategy provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteStrategy(ctx context.Context, strategyID bson.ObjectID) error {
	ret := _mock.Called(ctx, strategyID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteStrategy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bson.ObjectID) error); ok {
		r0 = returnFunc(ctx, strategyID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeleteStrategy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteStrategy'
type MockRepository_DeleteStrategy_Call struct {
	*mock.Call
}

// DeleteStrategy is a helper method to define mock.On call
//   - ctx context.Context
//   - strategyID bson.ObjectID
func (_e *MockRepository_Expecter) DeleteStrategy(ctx interface{}, strategyID interface{}) *MockRepository_DeleteStrategy_Call {
	return &MockRepository_DeleteStrategy_Call{Call: _e.mock.On("DeleteStrategy", ctx, strategyID)}
}

func (_c *MockRepository_DeleteStrategy_Call) Run(run func(ctx context.Context, strategyID bson.ObjectID)) *MockRepository_DeleteStrategy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bson.ObjectID
		if args[1] != nil {
			arg1 = args[1].(bson.ObjectID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteStrategy_Call) Return(err error) *MockRepository_DeleteStrategy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteStrategy_Call) RunAndReturn(run func(ctx context.Context, strategyID bson.ObjectID) error) *MockRepository_DeleteStrategy_Call {
	_c.Call.Return(run)
	return _c
}

// InsertStrategyAndIntents provides a mock function for the type MockRepository
func (_mock *MockRepository) InsertStrategyAndIntents(ctx context.Context, strategy *ScheduleStrategy, intents []*ScheduleIntent) error {
	ret := _mock.Called(ctx, strategy, intents)

	if len(ret) == 0 {
		panic("no return value specified for InsertStrategyAndIntents")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ScheduleStrategy, []*ScheduleIntent) error); ok {
		r0 = returnFunc(ctx, strategy, intents)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_InsertStrategyAndIntents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertStrategyAndIntents'
type MockRepository_InsertStrategyAndIntents_Call struct {
	*mock.Call
}

// InsertStrategyAndIntents is a helper method to define mock.On call
//   - ctx context.Context
//   - strategy *ScheduleStrategy
//   - intents []*ScheduleIntent
func (_e *MockRepository_Expecter) InsertStrategyAndIntents(ctx interface{}, strategy interface{}, intents interface{}) *MockRepository_InsertStrategyAndIntents_Call {
	return &MockRepository_InsertStrategyAndIntents_Call{Call: _e.mock.On("InsertStrategyAndIntents", ctx, strategy, intents)}
}

func (_c *MockRepository_InsertStrategyAndIntents_Call) Run(run func(ctx context.Context, strategy *ScheduleStrategy, intents []*ScheduleIntent)) *MockRepository_InsertStrategyAndIntents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ScheduleStrategy
		if args[1] != nil {
			arg1 = args[1].(*ScheduleStrategy)
		}
		var arg2 []*ScheduleIntent
		if args[2] != nil {
			arg2 = args[2].([]*ScheduleIntent)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_InsertStrategyAndIntents_Call) Return(err error) *MockRepository_InsertStrategyAndIntents_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_InsertStrategyAndIntents_Call) RunAndReturn(run func(ctx context.Context, strategy *ScheduleStrategy, intents []*ScheduleIntent) error) *MockRepository_InsertStrategyAndIntents_Call {
	_c.Call.Return(run)
	return _c
}

// QueryAuditLogs provides a mock function for the type MockRepository
func (_mock *MockRepository) QueryAuditLogs(ctx context.Context, opt *QueryAuditLogOptions) error {
	ret := _mock.Called(ctx, opt)

	if len(ret) == 0 {
		panic("no return value specified for QueryAuditLogs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *QueryAuditLogOptions) error); ok {
		r0 = returnFunc(ctx, opt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_QueryAuditLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryAuditLogs'
type MockRepository_QueryAuditLogs_Call struct {
	*mock.Call
}

// QueryAuditLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - opt *QueryAuditLogOptions
func (_e *MockRepository_Expecter) QueryAuditLogs(ctx interface{}, opt interface{}) *MockRepository_QueryAuditLogs_Call {
	return &MockRepository_QueryAuditLogs_Call{Call: _e.mock.On("QueryAuditLogs", ctx, opt)}
}

func (_c *MockRepository_QueryAuditLogs_Call) Run(run func(ctx context.Context, opt *QueryAuditLogOptions)) *MockRepository_QueryAuditLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *QueryAuditLogOptions
		if args[1] != nil {
			arg1 = args[1].(*QueryAuditLogOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_QueryAuditLogs_Call) Return(err error) *MockRepository_QueryAuditLogs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_QueryAuditLogs_Call) RunAndReturn(run func(ctx context.Context, opt *QueryAuditLogOptions) error) *MockRepository_QueryAuditLogs_Call {
	_c.Call.Return(run)
	return _c
}

// QueryIntents provides a mock function for the type MockRepository
func (_mock *MockRepository) QueryIntents(ctx context.Context, opt *QueryIntentOptions) error {
	ret := _mock.Called(ctx, opt)

	if len(ret) == 0 {
		panic("no return value specified for QueryIntents")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *QueryIntentOptions) error); ok {
		r0 = returnFunc(ctx, opt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_QueryIntents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryIntents'
type MockRepository_QueryIntents_Call struct {
	*mock.Call
}

// QueryIntents is a helper method to define mock.On call
//   - ctx context.Context
//   - opt *QueryIntentOptions
func (_e *MockRepository_Expecter) QueryIntents(ctx interface{}, opt interface{}) *MockRepository_QueryIntents_Call {
	return &MockRepository_QueryIntents_Call{Call: _e.mock.On("QueryIntents", ctx, opt)}
}

func (_c *MockRepository_QueryIntents_Call) Run(run func(ctx context.Context, opt *QueryIntentOptions)) *MockRepository_QueryIntents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *QueryIntentOptions
		if args[1] != nil {
			arg1 = args[1].(*QueryIntentOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_QueryIntents_Call) Return(err error) *MockRepository_QueryIntents_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_QueryIntents_Call) RunAndReturn(run func(ctx context.Context, opt *QueryIntentOptions) error) *MockRepository_QueryIntents_Call {
	_c.Call.Return(run)
	return _c
}

// QueryPermissions provides a mock function for the type MockRepository
func (_mock *MockRepository) QueryPermissions(ctx context.Context, opt *QueryPermissionOptions) error {
	ret := _mock.Called(ctx, opt)

	if len(ret) == 0 {
		panic("no return value specified for QueryPermissions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *QueryPermissionOptions) error); ok {
		r0 = returnFunc(ctx, opt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_QueryPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryPermissions'
type MockRepository_QueryPermissions_Call struct {
	*mock.Call
}

// QueryPermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - opt *QueryPermissionOptions
func (_e *MockRepository_Expecter) QueryPermissions(ctx interface{}, opt interface{}) *MockRepository_QueryPermissions_Call {
	return &MockRepository_QueryPermissions_Call{Call: _e.mock.On("QueryPermissions", ctx, opt)}
}

func (_c *MockRepository_QueryPermissions_Call) Run(run func(ctx context.Context, opt *QueryPermissionOptions)) *MockRepository_QueryPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *QueryPermissionOptions
		if args[1] != nil {
			arg1 = args[1].(*QueryPermissionOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_QueryPermissions_Call) Return(err error) *MockRepository_QueryPermissions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_QueryPermissions_Call) RunAndReturn(run func(ctx context.Context, opt *QueryPermissionOptions) error) *MockRepository_QueryPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRoles provides a mock function for the type MockRepository
func (_mock *MockRepository) QueryRoles(ctx context.Context, opt *QueryRoleOptions) error {
	ret := _mock.Called(ctx, opt)

	if len(ret) == 0 {
		panic("no return value specified for QueryRoles")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *QueryRoleOptions) error); ok {
		r0 = returnFunc(ctx, opt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_QueryRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRoles'
type MockRepository_QueryRoles_Call struct {
	*mock.Call
}

// QueryRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - opt *QueryRoleOptions
func (_e *MockRepository_Expecter) QueryRoles(ctx interface{}, opt interface{}) *MockRepository_QueryRoles_Call {
	return &MockRepository_QueryRoles_Call{Call: _e.mock.On("QueryRoles", ctx, opt)}
}

func (_c *MockRepository_QueryRoles_Call) Run(run func(ctx context.Context, opt *QueryRoleOptions)) *MockRepository_QueryRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *QueryRoleOptions
		if args[1] != nil {
			arg1 = args[1].(*QueryRoleOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_QueryRoles_Call) Return(err error) *MockRepository_QueryRoles_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_QueryRoles_Call) RunAndReturn(run func(ctx context.Context, opt *QueryRoleOptions) error) *MockRepository_QueryRoles_Call {
	_c.Call.Return(run)
	return _c
}

// QueryStrategies provides a mock function for the type MockRepository
func (_mock *MockRepository) QueryStrategies(ctx context.Context, opt *QueryStrategyOptions) error {
	ret := _mock.Called(ctx, opt)

	if len(ret) == 0 {
		panic("no return value specified for QueryStrategies")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *QueryStrategyOptions) error); ok {
		r0 = returnFunc(ctx, opt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_QueryStrategies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryStrategies'
type MockRepository_QueryStrategies_Call struct {
	*mock.Call
}

// QueryStrategies is a helper method to define mock.On call
//   - ctx context.Context
//   - opt *QueryStrategyOptions
func (_e *MockRepository_Expecter) QueryStrategies(ctx interface{}, opt interface{}) *MockRepository_QueryStrategies_Call {
	return &MockRepository_QueryStrategies_Call{Call: _e.mock.On("QueryStrategies", ctx, opt)}
}

func (_c *MockRepository_QueryStrategies_Call) Run(run func(ctx context.Context, opt *QueryStrategyOptions)) *MockRepository_QueryStrategies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *QueryStrategyOptions
		if args[1] != nil {
			arg1 = args[1].(*QueryStrategyOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_QueryStrategies_Call) Return(err error) *MockRepository_QueryStrategies_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_QueryStrategies_Call) RunAndReturn(run func(ctx context.Context, opt *QueryStrategyOptions) error) *MockRepository_QueryStrategies_Call {
	_c.Call.Return(run)
	return _c
}

// QueryUsers provides a mock function for the type MockRepository
func (_mock *MockRepository) QueryUsers(ctx context.Context, opt *QueryUserOptions) error {
	ret := _mock.Called(ctx, opt)

	if len(ret) == 0 {
		panic("no return value specified for QueryUsers")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *QueryUserOptions) error); ok {
		r0 = returnFunc(ctx, opt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_QueryUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryUsers'
type MockRepository_QueryUsers_Call struct {
	*mock.Call
}

// QueryUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - opt *QueryUserOptions
func (_e *MockRepository_Expecter) QueryUsers(ctx interface{}, opt interface{}) *MockRepository_QueryUsers_Call {
	return &MockRepository_QueryUsers_Call{Call: _e.mock.On("QueryUsers", ctx, opt)}
}

func (_c *MockRepository_QueryUsers_Call) Run(run func(ctx context.Context, opt *QueryUserOptions)) *MockRepository_QueryUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *QueryUserOptions
		if args[1] != nil {
			arg1 = args[1].(*QueryUserOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_QueryUsers_Call) Return(err error) *MockRepository_QueryUsers_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_QueryUsers_Call) RunAndReturn(run func(ctx context.Context, opt *QueryUserOptions) error) *MockRepository_QueryUsers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePermission provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdatePermission(ctx context.Context, permission *Permission) error {
	ret := _mock.Called(ctx, permission)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePermission")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Permission) error); ok {
		r0 = returnFunc(ctx, permission)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdatePermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePermission'
type MockRepository_UpdatePermission_Call struct {
	*mock.Call
}

// UpdatePermission is a helper method to define mock.On call
//   - ctx context.Context
//   - permission *Permission
func (_e *MockRepository_Expecter) UpdatePermission(ctx interface{}, permission interface{}) *MockRepository_UpdatePermission_Call {
	return &MockRepository_UpdatePermission_Call{Call: _e.mock.On("UpdatePermission", ctx, permission)}
}

func (_c *MockRepository_UpdatePermission_Call) Run(run func(ctx context.Context, permission *Permission)) *MockRepository_UpdatePermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Permission
		if args[1] != nil {
			arg1 = args[1].(*Permission)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_UpdatePermission_Call) Return(err error) *MockRepository_UpdatePermission_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdatePermission_Call) RunAndReturn(run func(ctx context.Context, permission *Permission) error) *MockRepository_UpdatePermission_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRole provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateRole(ctx context.Context, role *Role) error {
	ret := _mock.Called(ctx, role)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Role) error); ok {
		r0 = returnFunc(ctx, role)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRole'
type MockRepository_UpdateRole_Call struct {
	*mock.Call
}

// UpdateRole is a helper method to define mock.On call
//   - ctx context.Context
//   - role *Role
func (_e *MockRepository_Expecter) UpdateRole(ctx interface{}, role interface{}) *MockRepository_UpdateRole_Call {
	return &MockRepository_UpdateRole_Call{Call: _e.mock.On("UpdateRole", ctx, role)}
}

func (_c *MockRepository_UpdateRole_Call) Run(run func(ctx context.Context, role *Role)) *MockRepository_UpdateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Role
		if args[1] != nil {
			arg1 = args[1].(*Role)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateRole_Call) Return(err error) *MockRepository_UpdateRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdateRole_Call) RunAndReturn(run func(ctx context.Context, role *Role) error) *MockRepository_UpdateRole_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateUser(ctx context.Context, user *User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockRepository_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *User
func (_e *MockRepository_Expecter) UpdateUser(ctx interface{}, user interface{}) *MockRepository_UpdateUser_Call {
	return &MockRepository_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, user)}
}

func (_c *MockRepository_UpdateUser_Call) Run(run func(ctx context.Context, user *User)) *MockRepository_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *User
		if args[1] != nil {
			arg1 = args[1].(*User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateUser_Call) Return(err error) *MockRepository_UpdateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdateUser_Call) RunAndReturn(run func(ctx context.Context, user *User) error) *MockRepository_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// ChangePassword provides a mock function for the type MockService
func (_mock *MockService) ChangePassword(ctx context.Context, user *Claims, oldPassword string, newPassword string) error {
	ret := _mock.Called(ctx, user, oldPassword, newPassword)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Claims, string, string) error); ok {
		r0 = returnFunc(ctx, user, oldPassword, newPassword)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_ChangePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangePassword'
type MockService_ChangePassword_Call struct {
	*mock.Call
}

// ChangePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - user *Claims
//   - oldPassword string
//   - newPassword string
func (_e *MockService_Expecter) ChangePassword(ctx interface{}, user interface{}, oldPassword interface{}, newPassword interface{}) *MockService_ChangePassword_Call {
	return &MockService_ChangePassword_Call{Call: _e.mock.On("ChangePassword", ctx, user, oldPassword, newPassword)}
}

func (_c *MockService_ChangePassword_Call) Run(run func(ctx context.Context, user *Claims, oldPassword string, newPassword string)) *MockService_ChangePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Claims
		if args[1] != nil {
			arg1 = args[1].(*Claims)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_ChangePassword_Call) Return(err error) *MockService_ChangePassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_ChangePassword_Call) RunAndReturn(run func(ctx context.Context, user *Claims, oldPassword string, newPassword string) error) *MockService_ChangePassword_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAdminUserIfNotExists provides a mock function for the type MockService
func (_mock *MockService) CreateAdminUserIfNotExists(ctx context.Context, username string, password string) error {
	ret := _mock.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for CreateAdminUserIfNotExists")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, username, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_CreateAdminUserIfNotExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAdminUserIfNotExists'
type MockService_CreateAdminUserIfNotExists_Call struct {
	*mock.Call
}

// CreateAdminUserIfNotExists is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *MockService_Expecter) CreateAdminUserIfNotExists(ctx interface{}, username interface{}, password interface{}) *MockService_CreateAdminUserIfNotExists_Call {
	return &MockService_CreateAdminUserIfNotExists_Call{Call: _e.mock.On("CreateAdminUserIfNotExists", ctx, username, password)}
}

func (_c *MockService_CreateAdminUserIfNotExists_Call) Run(run func(ctx context.Context, username string, password string)) *MockService_CreateAdminUserIfNotExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_CreateAdminUserIfNotExists_Call) Return(err error) *MockService_CreateAdminUserIfNotExists_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_CreateAdminUserIfNotExists_Call) RunAndReturn(run func(ctx context.Context, username string, password string) error) *MockService_CreateAdminUserIfNotExists_Call {
	_c.Call.Return(run)
	return _c
}

// CreateNewUser provides a mock function for the type MockService
func (_mock *MockService) CreateNewUser(ctx context.Context, operator *Claims, username string, password string) error {
	ret := _mock.Called(ctx, operator, username, password)

	if len(ret) == 0 {
		panic("no return value specified for CreateNewUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Claims, string, string) error); ok {
		r0 = returnFunc(ctx, operator, username, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_CreateNewUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNewUser'
type MockService_CreateNewUser_Call struct {
	*mock.Call
}

// CreateNewUser is a helper method to define mock.On call
//   - ctx context.Context
//   - operator *Claims
//   - username string
//   - password string
func (_e *MockService_Expecter) CreateNewUser(ctx interface{}, operator interface{}, username interface{}, password interface{}) *MockService_CreateNewUser_Call {
	return &MockService_CreateNewUser_Call{Call: _e.mock.On("CreateNewUser", ctx, operator, username, password)}
}

func (_c *MockService_CreateNewUser_Call) Run(run func(ctx context.Context, operator *Claims, username string, password string)) *MockService_CreateNewUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Claims
		if args[1] != nil {
			arg1 = args[1].(*Claims)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_CreateNewUser_Call) Return(err error) *MockService_CreateNewUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_CreateNewUser_Call) RunAndReturn(run func(ctx context.Context, operator *Claims, username string, password string) error) *MockService_CreateNewUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRole provides a mock function for the type MockService
func (_mock *MockService) CreateRole(ctx context.Context, operator *Claims, role *Role) error {
	ret := _mock.Called(ctx, operator, role)

	if len(ret) == 0 {
		panic("no return value specified for CreateRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Claims, *Role) error); ok {
		r0 = returnFunc(ctx, operator, role)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_CreateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRole'
type MockService_CreateRole_Call struct {
	*mock.Call
}

// CreateRole is a helper method to define mock.On call
//   - ctx context.Context
//   - operator *Claims
//   - role *Role
func (_e *MockService_Expecter) CreateRole(ctx interface{}, operator interface{}, role interface{}) *MockService_CreateRole_Call {
	return &MockService_CreateRole_Call{Call: _e.mock.On("CreateRole", ctx, operator, role)}
}

func (_c *MockService_CreateRole_Call) Run(run func(ctx context.Context, operator *Claims, role *Role)) *MockService_CreateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Claims
		if args[1] != nil {
			arg1 = args[1].(*Claims)
		}
		var arg2 *Role
		if args[2] != nil {
			arg2 = args[2].(*Role)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_CreateRole_Call) Return(err error) *MockService_CreateRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_CreateRole_Call) RunAndReturn(run func(ctx context.Context, operator *Claims, role *Role) error) *MockService_CreateRole_Call {
	_c.Call.Return(run)
	return _c
}

// CreateScheduleStrategy provides a mock function for the type MockService
func (_mock *MockService) CreateScheduleStrategy(ctx context.Context, operator *Claims, strategy *ScheduleStrategy) error {
	ret := _mock.Called(ctx, operator, strategy)

	if len(ret) == 0 {
		panic("no return value specified for CreateScheduleStrategy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Claims, *ScheduleStrategy) error); ok {
		r0 = returnFunc(ctx, operator, strategy)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_CreateScheduleStrategy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateScheduleStrategy'
type MockService_CreateScheduleStrategy_Call struct {
	*mock.Call
}

// CreateScheduleStrategy is a helper method to define mock.On call
//   - ctx context.Context
//   - operator *Claims
//   - strategy *ScheduleStrategy
func (_e *MockService_Expecter) CreateScheduleStrategy(ctx interface{}, operator interface{}, strategy interface{}) *MockService_CreateScheduleStrategy_Call {
	return &MockService_CreateScheduleStrategy_Call{Call: _e.mock.On("CreateScheduleStrategy", ctx, operator, strategy)}
}

func (_c *MockService_CreateScheduleStrategy_Call) Run(run func(ctx context.Context, operator *Claims, strategy *ScheduleStrategy)) *MockService_CreateScheduleStrategy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Claims
		if args[1] != nil {
			arg1 = args[1].(*Claims)
		}
		var arg2 *ScheduleStrategy
		if args[2] != nil {
			arg2 = args[2].(*ScheduleStrategy)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_CreateScheduleStrategy_Call) Return(err error) *MockService_CreateScheduleStrategy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_CreateScheduleStrategy_Call) RunAndReturn(run func(ctx context.Context, operator *Claims, strategy *ScheduleStrategy) error) *MockService_CreateScheduleStrategy_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRole provides a mock function for the type MockService
func (_mock *MockService) DeleteRole(ctx context.Context, operator *Claims, roleID string) error {
	ret := _mock.Called(ctx, operator, roleID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Claims, string) error); ok {
		r0 = returnFunc(ctx, operator, roleID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRole'
type MockService_DeleteRole_Call struct {
	*mock.Call
}

// DeleteRole is a helper method to define mock.On call
//   - ctx context.Context
//   - operator *Claims
//   - roleID string
func (_e *MockService_Expecter) DeleteRole(ctx interface{}, operator interface{}, roleID interface{}) *MockService_DeleteRole_Call {
	return &MockService_DeleteRole_Call{Call: _e.mock.On("DeleteRole", ctx, operator, roleID)}
}

func (_c *MockService_DeleteRole_Call) Run(run func(ctx context.Context, operator *Claims, roleID string)) *MockService_DeleteRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Claims
		if args[1] != nil {
			arg1 = args[1].(*Claims)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_DeleteRole_Call) Return(err error) *MockService_DeleteRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteRole_Call) RunAndReturn(run func(ctx context.Context, operator *Claims, roleID string) error) *MockService_DeleteRole_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteScheduleIntents provides a mock function for the type MockService
func (_mock *MockService) DeleteScheduleIntents(ctx context.Context, operator *Claims, intentIDs []string) error {
	ret := _mock.Called(ctx, operator, intentIDs)

	if len(ret) == 0 {
		panic("no return value specified for DeleteScheduleIntents")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Claims, []string) error); ok {
		r0 = returnFunc(ctx, operator, intentIDs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteScheduleIntents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteScheduleIntents'
type MockService_DeleteScheduleIntents_Call struct {
	*mock.Call
}

// DeleteScheduleIntents is a helper method to define mock.On call
//   - ctx context.Context
//   - operator *Claims
//   - intentIDs []string
func (_e *MockService_Expecter) DeleteScheduleIntents(ctx interface{}, operator interface{}, intentIDs interface{}) *MockService_DeleteScheduleIntents_Call {
	return &MockService_DeleteScheduleIntents_Call{Call: _e.mock.On("DeleteScheduleIntents", ctx, operator, intentIDs)}
}

func (_c *MockService_DeleteScheduleIntents_Call) Run(run func(ctx context.Context, operator *Claims, intentIDs []string)) *MockService_DeleteScheduleIntents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Claims
		if args[1] != nil {
			arg1 = args[1].(*Claims)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_DeleteScheduleIntents_Call) Return(err error) *MockService_DeleteScheduleIntents_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteScheduleIntents_Call) RunAndReturn(run func(ctx context.Context, operator *Claims, intentIDs []string) error) *MockService_DeleteScheduleIntents_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteScheduleStrategy provides a mock function for the type MockService
func (_mock *MockService) DeleteScheduleStrategy(ctx context.Context, operator *Claims, strategyID string) error {
	ret := _mock.Called(ctx, operator, strategyID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteScheduleStrategy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Claims, string) error); ok {
		r0 = returnFunc(ctx, operator, strategyID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteScheduleStrategy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteScheduleStrategy'
type MockService_DeleteScheduleStrategy_Call struct {
	*mock.Call
}

// DeleteScheduleStrategy is a helper method to define mock.On call
//   - ctx context.Context
//   - operator *Claims
//   - strategyID string
func (_e *MockService_Expecter) DeleteScheduleStrategy(ctx interface{}, operator interface{}, strategyID interface{}) *MockService_DeleteScheduleStrategy_Call {
	return &MockService_DeleteScheduleStrategy_Call{Call: _e.mock.On("DeleteScheduleStrategy", ctx, operator, strategyID)}
}

func (_c *MockService_DeleteScheduleStrategy_Call) Run(run func(ctx context.Context, operator *Claims, strategyID string)) *MockService_DeleteScheduleStrategy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Claims
		if args[1] != nil {
			arg1 = args[1].(*Claims)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_DeleteScheduleStrategy_Call) Return(err error) *MockService_DeleteScheduleStrategy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteScheduleStrategy_Call) RunAndReturn(run func(ctx context.Context, operator *Claims, strategyID string) error) *MockService_DeleteScheduleStrategy_Call {
	_c.Call.Return(run)
	return _c
}

// GetPodPIDMapping provides a mock function for the type MockService
func (_mock *MockService) GetPodPIDMapping(ctx context.Context, nodeID string) (*PodPIDMappingResponse, error) {
	ret := _mock.Called(ctx, nodeID)

	if len(ret) == 0 {
		panic("no return value specified for GetPodPIDMapping")
	}

	var r0 *PodPIDMappingResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*PodPIDMappingResponse, error)); ok {
		return returnFunc(ctx, nodeID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *PodPIDMappingResponse); ok {
		r0 = returnFunc(ctx, nodeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*PodPIDMappingResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, nodeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetPodPIDMapping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPodPIDMapping'
type MockService_GetPodPIDMapping_Call struct {
	*mock.Call
}

// GetPodPIDMapping is a helper method to define mock.On call
//   - ctx context.Context
//   - nodeID string
func (_e *MockService_Expecter) GetPodPIDMapping(ctx interface{}, nodeID interface{}) *MockService_GetPodPIDMapping_Call {
	return &MockService_GetPodPIDMapping_Call{Call: _e.mock.On("GetPodPIDMapping", ctx, nodeID)}
}

func (_c *MockService_GetPodPIDMapping_Call) Run(run func(ctx context.Context, nodeID string)) *MockService_GetPodPIDMapping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetPodPIDMapping_Call) Return(podPIDMappingResponse *PodPIDMappingResponse, err error) *MockService_GetPodPIDMapping_Call {
	_c.Call.Return(podPIDMappingResponse, err)
	return _c
}

func (_c *MockService_GetPodPIDMapping_Call) RunAndReturn(run func(ctx context.Context, nodeID string) (*PodPIDMappingResponse, error)) *MockService_GetPodPIDMapping_Call {
	_c.Call.Return(run)
	return _c
}

// ListNodes provides a mock function for the type MockService
func (_mock *MockService) ListNodes(ctx context.Context) ([]*Node, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListNodes")
	}

	var r0 []*Node
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*Node, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*Node); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Node)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListNodes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNodes'
type MockService_ListNodes_Call struct {
	*mock.Call
}

// ListNodes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) ListNodes(ctx interface{}) *MockService_ListNodes_Call {
	return &MockService_ListNodes_Call{Call: _e.mock.On("ListNodes", ctx)}
}

func (_c *MockService_ListNodes_Call) Run(run func(ctx context.Context)) *MockService_ListNodes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_ListNodes_Call) Return(nodes []*Node, err error) *MockService_ListNodes_Call {
	_c.Call.Return(nodes, err)
	return _c
}

func (_c *MockService_ListNodes_Call) RunAndReturn(run func(ctx context.Context) ([]*Node, error)) *MockService_ListNodes_Call {
	_c.Call.Return(run)
	return _c
}

// ListScheduleIntents provides a mock function for the type MockService
func (_mock *MockService) ListScheduleIntents(ctx context.Context, filterOpts *QueryIntentOptions) error {
	ret := _mock.Called(ctx, filterOpts)

	if len(ret) == 0 {
		panic("no return value specified for ListScheduleIntents")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *QueryIntentOptions) error); ok {
		r0 = returnFunc(ctx, filterOpts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_ListScheduleIntents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListScheduleIntents'
type MockService_ListScheduleIntents_Call struct {
	*mock.Call
}

// ListScheduleIntents is a helper method to define mock.On call
//   - ctx context.Context
//   - filterOpts *QueryIntentOptions
func (_e *MockService_Expecter) ListScheduleIntents(ctx interface{}, filterOpts interface{}) *MockService_ListScheduleIntents_Call {
	return &MockService_ListScheduleIntents_Call{Call: _e.mock.On("ListScheduleIntents", ctx, filterOpts)}
}

func (_c *MockService_ListScheduleIntents_Call) Run(run func(ctx context.Context, filterOpts *QueryIntentOptions)) *MockService_ListScheduleIntents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *QueryIntentOptions
		if args[1] != nil {
			arg1 = args[1].(*QueryIntentOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_ListScheduleIntents_Call) Return(err error) *MockService_ListScheduleIntents_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_ListScheduleIntents_Call) RunAndReturn(run func(ctx context.Context, filterOpts *QueryIntentOptions) error) *MockService_ListScheduleIntents_Call {
	_c.Call.Return(run)
	return _c
}

// ListScheduleStrategies provides a mock function for the type MockService
func (_mock *MockService) ListScheduleStrategies(ctx context.Context, filterOpts *QueryStrategyOptions) error {
	ret := _mock.Called(ctx, filterOpts)

	if len(ret) == 0 {
		panic("no return value specified for ListScheduleStrategies")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *QueryStrategyOptions) error); ok {
		r0 = returnFunc(ctx, filterOpts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_ListScheduleStrategies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListScheduleStrategies'
type MockService_ListScheduleStrategies_Call struct {
	*mock.Call
}

// ListScheduleStrategies is a helper method to define mock.On call
//   - ctx context.Context
//   - filterOpts *QueryStrategyOptions
func (_e *MockService_Expecter) ListScheduleStrategies(ctx interface{}, filterOpts interface{}) *MockService_ListScheduleStrategies_Call {
	return &MockService_ListScheduleStrategies_Call{Call: _e.mock.On("ListScheduleStrategies", ctx, filterOpts)}
}

func (_c *MockService_ListScheduleStrategies_Call) Run(run func(ctx context.Context, filterOpts *QueryStrategyOptions)) *MockService_ListScheduleStrategies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *QueryStrategyOptions
		if args[1] != nil {
			arg1 = args[1].(*QueryStrategyOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_ListScheduleStrategies_Call) Return(err error) *MockService_ListScheduleStrategies_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_ListScheduleStrategies_Call) RunAndReturn(run func(ctx context.Context, filterOpts *QueryStrategyOptions) error) *MockService_ListScheduleStrategies_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type MockService
func (_mock *MockService) Login(ctx context.Context, email string, password string) (string, error) {
	ret := _mock.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, email, password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *MockService_Expecter) Login(ctx interface{}, email interface{}, password interface{}) *MockService_Login_Call {
	return &MockService_Login_Call{Call: _e.mock.On("Login", ctx, email, password)}
}

func (_c *MockService_Login_Call) Run(run func(ctx context.Context, email string, password string)) *MockService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Login_Call) Return(token string, err error) *MockService_Login_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockService_Login_Call) RunAndReturn(run func(ctx context.Context, email string, password string) (string, error)) *MockService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// QueryPermissions provides a mock function for the type MockService
func (_mock *MockService) QueryPermissions(ctx context.Context, opt *QueryPermissionOptions) error {
	ret := _mock.Called(ctx, opt)

	if len(ret) == 0 {
		panic("no return value specified for QueryPermissions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *QueryPermissionOptions) error); ok {
		r0 = returnFunc(ctx, opt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_QueryPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryPermissions'
type MockService_QueryPermissions_Call struct {
	*mock.Call
}

// QueryPermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - opt *QueryPermissionOptions
func (_e *MockService_Expecter) QueryPermissions(ctx interface{}, opt interface{}) *MockService_QueryPermissions_Call {
	return &MockService_QueryPermissions_Call{Call: _e.mock.On("QueryPermissions", ctx, opt)}
}

func (_c *MockService_QueryPermissions_Call) Run(run func(ctx context.Context, opt *QueryPermissionOptions)) *MockService_QueryPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *QueryPermissionOptions
		if args[1] != nil {
			arg1 = args[1].(*QueryPermissionOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_QueryPermissions_Call) Return(err error) *MockService_QueryPermissions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_QueryPermissions_Call) RunAndReturn(run func(ctx context.Context, opt *QueryPermissionOptions) error) *MockService_QueryPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRoles provides a mock function for the type MockService
func (_mock *MockService) QueryRoles(ctx context.Context, opt *QueryRoleOptions) error {
	ret := _mock.Called(ctx, opt)

	if len(ret) == 0 {
		panic("no return value specified for QueryRoles")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *QueryRoleOptions) error); ok {
		r0 = returnFunc(ctx, opt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_QueryRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRoles'
type MockService_QueryRoles_Call struct {
	*mock.Call
}

// QueryRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - opt *QueryRoleOptions
func (_e *MockService_Expecter) QueryRoles(ctx interface{}, opt interface{}) *MockService_QueryRoles_Call {
	return &MockService_QueryRoles_Call{Call: _e.mock.On("QueryRoles", ctx, opt)}
}

func (_c *MockService_QueryRoles_Call) Run(run func(ctx context.Context, opt *QueryRoleOptions)) *MockService_QueryRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *QueryRoleOptions
		if args[1] != nil {
			arg1 = args[1].(*QueryRoleOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_QueryRoles_Call) Return(err error) *MockService_QueryRoles_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_QueryRoles_Call) RunAndReturn(run func(ctx context.Context, opt *QueryRoleOptions) error) *MockService_QueryRoles_Call {
	_c.Call.Return(run)
	return _c
}

// QueryUsers provides a mock function for the type MockService
func (_mock *MockService) QueryUsers(ctx context.Context, opt *QueryUserOptions) error {
	ret := _mock.Called(ctx, opt)

	if len(ret) == 0 {
		panic("no return value specified for QueryUsers")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *QueryUserOptions) error); ok {
		r0 = returnFunc(ctx, opt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_QueryUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryUsers'
type MockService_QueryUsers_Call struct {
	*mock.Call
}

// QueryUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - opt *QueryUserOptions
func (_e *MockService_Expecter) QueryUsers(ctx interface{}, opt interface{}) *MockService_QueryUsers_Call {
	return &MockService_QueryUsers_Call{Call: _e.mock.On("QueryUsers", ctx, opt)}
}

func (_c *MockService_QueryUsers_Call) Run(run func(ctx context.Context, opt *QueryUserOptions)) *MockService_QueryUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *QueryUserOptions
		if args[1] != nil {
			arg1 = args[1].(*QueryUserOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_QueryUsers_Call) Return(err error) *MockService_QueryUsers_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_QueryUsers_Call) RunAndReturn(run func(ctx context.Context, opt *QueryUserOptions) error) *MockService_QueryUsers_Call {
	_c.Call.Return(run)
	return _c
}

// ResetPassword provides a mock function for the type MockService
func (_mock *MockService) ResetPassword(ctx context.Context, operator *Claims, id string, newPassword string) error {
	ret := _mock.Called(ctx, operator, id, newPassword)

	if len(ret) == 0 {
		panic("no return value specified for ResetPassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Claims, string, string) error); ok {
		r0 = returnFunc(ctx, operator, id, newPassword)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_ResetPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetPassword'
type MockService_ResetPassword_Call struct {
	*mock.Call
}

// ResetPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - operator *Claims
//   - id string
//   - newPassword string
func (_e *MockService_Expecter) ResetPassword(ctx interface{}, operator interface{}, id interface{}, newPassword interface{}) *MockService_ResetPassword_Call {
	return &MockService_ResetPassword_Call{Call: _e.mock.On("ResetPassword", ctx, operator, id, newPassword)}
}

func (_c *MockService_ResetPassword_Call) Run(run func(ctx context.Context, operator *Claims, id string, newPassword string)) *MockService_ResetPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Claims
		if args[1] != nil {
			arg1 = args[1].(*Claims)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_ResetPassword_Call) Return(err error) *MockService_ResetPassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_ResetPassword_Call) RunAndReturn(run func(ctx context.Context, operator *Claims, id string, newPassword string) error) *MockService_ResetPassword_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRole provides a mock function for the type MockService
func (_mock *MockService) UpdateRole(ctx context.Context, operator *Claims, roleID string, opt UpdateRoleOptions) error {
	ret := _mock.Called(ctx, operator, roleID, opt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Claims, string, UpdateRoleOptions) error); ok {
		r0 = returnFunc(ctx, operator, roleID, opt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_UpdateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRole'
type MockService_UpdateRole_Call struct {
	*mock.Call
}

// UpdateRole is a helper method to define mock.On call
//   - ctx context.Context
//   - operator *Claims
//   - roleID string
//   - opt UpdateRoleOptions
func (_e *MockService_Expecter) UpdateRole(ctx interface{}, operator interface{}, roleID interface{}, opt interface{}) *MockService_UpdateRole_Call {
	return &MockService_UpdateRole_Call{Call: _e.mock.On("UpdateRole", ctx, operator, roleID, opt)}
}

func (_c *MockService_UpdateRole_Call) Run(run func(ctx context.Context, operator *Claims, roleID string, opt UpdateRoleOptions)) *MockService_UpdateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Claims
		if args[1] != nil {
			arg1 = args[1].(*Claims)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 UpdateRoleOptions
		if args[3] != nil {
			arg3 = args[3].(UpdateRoleOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_UpdateRole_Call) Return(err error) *MockService_UpdateRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_UpdateRole_Call) RunAndReturn(run func(ctx context.Context, operator *Claims, roleID string, opt UpdateRoleOptions) error) *MockService_UpdateRole_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserPermissions provides a mock function for the type MockService
func (_mock *MockService) UpdateUserPermissions(ctx context.Context, operator *Claims, id string, opt UpdateUserPermissionsOptions) error {
	ret := _mock.Called(ctx, operator, id, opt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserPermissions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Claims, string, UpdateUserPermissionsOptions) error); ok {
		r0 = returnFunc(ctx, operator, id, opt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_UpdateUserPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserPermissions'
type MockService_UpdateUserPermissions_Call struct {
	*mock.Call
}

// UpdateUserPermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - operator *Claims
//   - id string
//   - opt UpdateUserPermissionsOptions
func (_e *MockService_Expecter) UpdateUserPermissions(ctx interface{}, operator interface{}, id interface{}, opt interface{}) *MockService_UpdateUserPermissions_Call {
	return &MockService_UpdateUserPermissions_Call{Call: _e.mock.On("UpdateUserPermissions", ctx, operator, id, opt)}
}

func (_c *MockService_UpdateUserPermissions_Call) Run(run func(ctx context.Context, operator *Claims, id string, opt UpdateUserPermissionsOptions)) *MockService_UpdateUserPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Claims
		if args[1] != nil {
			arg1 = args[1].(*Claims)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 UpdateUserPermissionsOptions
		if args[3] != nil {
			arg3 = args[3].(UpdateUserPermissionsOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_UpdateUserPermissions_Call) Return(err error) *MockService_UpdateUserPermissions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_UpdateUserPermissions_Call) RunAndReturn(run func(ctx context.Context, operator *Claims, id string, opt UpdateUserPermissionsOptions) error) *MockService_UpdateUserPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyJWTToken provides a mock function for the type MockService
func (_mock *MockService) VerifyJWTToken(ctx context.Context, tokenString string, permissionKey PermissionKey) (Claims, RolePolicy, error) {
	ret := _mock.Called(ctx, tokenString, permissionKey)

	if len(ret) == 0 {
		panic("no return value specified for VerifyJWTToken")
	}

	var r0 Claims
	var r1 RolePolicy
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, PermissionKey) (Claims, RolePolicy, error)); ok {
		return returnFunc(ctx, tokenString, permissionKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, PermissionKey) Claims); ok {
		r0 = returnFunc(ctx, tokenString, permissionKey)
	} else {
		r0 = ret.Get(0).(Claims)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, PermissionKey) RolePolicy); ok {
		r1 = returnFunc(ctx, tokenString, permissionKey)
	} else {
		r1 = ret.Get(1).(RolePolicy)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, PermissionKey) error); ok {
		r2 = returnFunc(ctx, tokenString, permissionKey)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockService_VerifyJWTToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyJWTToken'
type MockService_VerifyJWTToken_Call struct {
	*mock.Call
}

// VerifyJWTToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenString string
//   - permissionKey PermissionKey
func (_e *MockService_Expecter) VerifyJWTToken(ctx interface{}, tokenString interface{}, permissionKey interface{}) *MockService_VerifyJWTToken_Call {
	return &MockService_VerifyJWTToken_Call{Call: _e.mock.On("VerifyJWTToken", ctx, tokenString, permissionKey)}
}

func (_c *MockService_VerifyJWTToken_Call) Run(run func(ctx context.Context, tokenString string, permissionKey PermissionKey)) *MockService_VerifyJWTToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 PermissionKey
		if args[2] != nil {
			arg2 = args[2].(PermissionKey)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_VerifyJWTToken_Call) Return(claims Claims, rolePolicy RolePolicy, err error) *MockService_VerifyJWTToken_Call {
	_c.Call.Return(claims, rolePolicy, err)
	return _c
}

func (_c *MockService_VerifyJWTToken_Call) RunAndReturn(run func(ctx context.Context, tokenString string, permissionKey PermissionKey) (Claims, RolePolicy, error)) *MockService_VerifyJWTToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockK8SAdapter creates a new instance of MockK8SAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockK8SAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockK8SAdapter {
	mock := &MockK8SAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockK8SAdapter is an autogenerated mock type for the K8SAdapter type
type MockK8SAdapter struct {
	mock.Mock
}

type MockK8SAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockK8SAdapter) EXPECT() *MockK8SAdapter_Expecter {
	return &MockK8SAdapter_Expecter{mock: &_m.Mock}
}

// ListNodes provides a mock function for the type MockK8SAdapter
func (_mock *MockK8SAdapter) ListNodes(ctx context.Context) ([]*Node, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListNodes")
	}

	var r0 []*Node
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*Node, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*Node); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Node)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockK8SAdapter_ListNodes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNodes'
type MockK8SAdapter_ListNodes_Call struct {
	*mock.Call
}

// ListNodes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockK8SAdapter_Expecter) ListNodes(ctx interface{}) *MockK8SAdapter_ListNodes_Call {
	return &MockK8SAdapter_ListNodes_Call{Call: _e.mock.On("ListNodes", ctx)}
}

func (_c *MockK8SAdapter_ListNodes_Call) Run(run func(ctx context.Context)) *MockK8SAdapter_ListNodes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockK8SAdapter_ListNodes_Call) Return(nodes []*Node, err error) *MockK8SAdapter_ListNodes_Call {
	_c.Call.Return(nodes, err)
	return _c
}

func (_c *MockK8SAdapter_ListNodes_Call) RunAndReturn(run func(ctx context.Context) ([]*Node, error)) *MockK8SAdapter_ListNodes_Call {
	_c.Call.Return(run)
	return _c
}

// QueryDecisionMakerPods provides a mock function for the type MockK8SAdapter
func (_mock *MockK8SAdapter) QueryDecisionMakerPods(ctx context.Context, opt *QueryDecisionMakerPodsOptions) ([]*DecisionMakerPod, error) {
	ret := _mock.Called(ctx, opt)

	if len(ret) == 0 {
		panic("no return value specified for QueryDecisionMakerPods")
	}

	var r0 []*DecisionMakerPod
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *QueryDecisionMakerPodsOptions) ([]*DecisionMakerPod, error)); ok {
		return returnFunc(ctx, opt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *QueryDecisionMakerPodsOptions) []*DecisionMakerPod); ok {
		r0 = returnFunc(ctx, opt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*DecisionMakerPod)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *QueryDecisionMakerPodsOptions) error); ok {
		r1 = returnFunc(ctx, opt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockK8SAdapter_QueryDecisionMakerPods_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryDecisionMakerPods'
type MockK8SAdapter_QueryDecisionMakerPods_Call struct {
	*mock.Call
}

// QueryDecisionMakerPods is a helper method to define mock.On call
//   - ctx context.Context
//   - opt *QueryDecisionMakerPodsOptions
func (_e *MockK8SAdapter_Expecter) QueryDecisionMakerPods(ctx interface{}, opt interface{}) *MockK8SAdapter_QueryDecisionMakerPods_Call {
	return &MockK8SAdapter_QueryDecisionMakerPods_Call{Call: _e.mock.On("QueryDecisionMakerPods", ctx, opt)}
}

func (_c *MockK8SAdapter_QueryDecisionMakerPods_Call) Run(run func(ctx context.Context, opt *QueryDecisionMakerPodsOptions)) *MockK8SAdapter_QueryDecisionMakerPods_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *QueryDecisionMakerPodsOptions
		if args[1] != nil {
			arg1 = args[1].(*QueryDecisionMakerPodsOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockK8SAdapter_QueryDecisionMakerPods_Call) Return(decisionMakerPods []*DecisionMakerPod, err error) *MockK8SAdapter_QueryDecisionMakerPods_Call {
	_c.Call.Return(decisionMakerPods, err)
	return _c
}

func (_c *MockK8SAdapter_QueryDecisionMakerPods_Call) RunAndReturn(run func(ctx context.Context, opt *QueryDecisionMakerPodsOptions) ([]*DecisionMakerPod, error)) *MockK8SAdapter_QueryDecisionMakerPods_Call {
	_c.Call.Return(run)
	return _c
}

// QueryPods provides a mock function for the type MockK8SAdapter
func (_mock *MockK8SAdapter) QueryPods(ctx context.Context, opt *QueryPodsOptions) ([]*Pod, error) {
	ret := _mock.Called(ctx, opt)

	if len(ret) == 0 {
		panic("no return value specified for QueryPods")
	}

	var r0 []*Pod
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *QueryPodsOptions) ([]*Pod, error)); ok {
		return returnFunc(ctx, opt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *QueryPodsOptions) []*Pod); ok {
		r0 = returnFunc(ctx, opt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Pod)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *QueryPodsOptions) error); ok {
		r1 = returnFunc(ctx, opt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockK8SAdapter_QueryPods_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryPods'
type MockK8SAdapter_QueryPods_Call struct {
	*mock.Call
}

// QueryPods is a helper method to define mock.On call
//   - ctx context.Context
//   - opt *QueryPodsOptions
func (_e *MockK8SAdapter_Expecter) QueryPods(ctx interface{}, opt interface{}) *MockK8SAdapter_QueryPods_Call {
	return &MockK8SAdapter_QueryPods_Call{Call: _e.mock.On("QueryPods", ctx, opt)}
}

func (_c *MockK8SAdapter_QueryPods_Call) Run(run func(ctx context.Context, opt *QueryPodsOptions)) *MockK8SAdapter_QueryPods_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *QueryPodsOptions
		if args[1] != nil {
			arg1 = args[1].(*QueryPodsOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockK8SAdapter_QueryPods_Call) Return(pods []*Pod, err error) *MockK8SAdapter_QueryPods_Call {
	_c.Call.Return(pods, err)
	return _c
}

func (_c *MockK8SAdapter_QueryPods_Call) RunAndReturn(run func(ctx context.Context, opt *QueryPodsOptions) ([]*Pod, error)) *MockK8SAdapter_QueryPods_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDecisionMakerAdapter creates a new instance of MockDecisionMakerAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDecisionMakerAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDecisionMakerAdapter {
	mock := &MockDecisionMakerAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDecisionMakerAdapter is an autogenerated mock type for the DecisionMakerAdapter type
type MockDecisionMakerAdapter struct {
	mock.Mock
}

type MockDecisionMakerAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDecisionMakerAdapter) EXPECT() *MockDecisionMakerAdapter_Expecter {
	return &MockDecisionMakerAdapter_Expecter{mock: &_m.Mock}
}

// DeleteSchedulingIntents provides a mock function for the type MockDecisionMakerAdapter
func (_mock *MockDecisionMakerAdapter) DeleteSchedulingIntents(ctx context.Context, decisionMaker *DecisionMakerPod, req *DeleteIntentsRequest) error {
	ret := _mock.Called(ctx, decisionMaker, req)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSchedulingIntents")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *DecisionMakerPod, *DeleteIntentsRequest) error); ok {
		r0 = returnFunc(ctx, decisionMaker, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDecisionMakerAdapter_DeleteSchedulingIntents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSchedulingIntents'
type MockDecisionMakerAdapter_DeleteSchedulingIntents_Call struct {
	*mock.Call
}

// DeleteSchedulingIntents is a helper method to define mock.On call
//   - ctx context.Context
//   - decisionMaker *DecisionMakerPod
//   - req *DeleteIntentsRequest
func (_e *MockDecisionMakerAdapter_Expecter) DeleteSchedulingIntents(ctx interface{}, decisionMaker interface{}, req interface{}) *MockDecisionMakerAdapter_DeleteSchedulingIntents_Call {
	return &MockDecisionMakerAdapter_DeleteSchedulingIntents_Call{Call: _e.mock.On("DeleteSchedulingIntents", ctx, decisionMaker, req)}
}

func (_c *MockDecisionMakerAdapter_DeleteSchedulingIntents_Call) Run(run func(ctx context.Context, decisionMaker *DecisionMakerPod, req *DeleteIntentsRequest)) *MockDecisionMakerAdapter_DeleteSchedulingIntents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *DecisionMakerPod
		if args[1] != nil {
			arg1 = args[1].(*DecisionMakerPod)
		}
		var arg2 *DeleteIntentsRequest
		if args[2] != nil {
			arg2 = args[2].(*DeleteIntentsRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDecisionMakerAdapter_DeleteSchedulingIntents_Call) Return(err error) *MockDecisionMakerAdapter_DeleteSchedulingIntents_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDecisionMakerAdapter_DeleteSchedulingIntents_Call) RunAndReturn(run func(ctx context.Context, decisionMaker *DecisionMakerPod, req *DeleteIntentsRequest) error) *MockDecisionMakerAdapter_DeleteSchedulingIntents_Call {
	_c.Call.Return(run)
	return _c
}

// GetIntentMerkleRoot provides a mock function for the type MockDecisionMakerAdapter
func (_mock *MockDecisionMakerAdapter) GetIntentMerkleRoot(ctx context.Context, decisionMaker *DecisionMakerPod) (string, error) {
	ret := _mock.Called(ctx, decisionMaker)

	if len(ret) == 0 {
		panic("no return value specified for GetIntentMerkleRoot")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *DecisionMakerPod) (string, error)); ok {
		return returnFunc(ctx, decisionMaker)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *DecisionMakerPod) string); ok {
		r0 = returnFunc(ctx, decisionMaker)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *DecisionMakerPod) error); ok {
		r1 = returnFunc(ctx, decisionMaker)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDecisionMakerAdapter_GetIntentMerkleRoot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIntentMerkleRoot'
type MockDecisionMakerAdapter_GetIntentMerkleRoot_Call struct {
	*mock.Call
}

// GetIntentMerkleRoot is a helper method to define mock.On call
//   - ctx context.Context
//   - decisionMaker *DecisionMakerPod
func (_e *MockDecisionMakerAdapter_Expecter) GetIntentMerkleRoot(ctx interface{}, decisionMaker interface{}) *MockDecisionMakerAdapter_GetIntentMerkleRoot_Call {
	return &MockDecisionMakerAdapter_GetIntentMerkleRoot_Call{Call: _e.mock.On("GetIntentMerkleRoot", ctx, decisionMaker)}
}

func (_c *MockDecisionMakerAdapter_GetIntentMerkleRoot_Call) Run(run func(ctx context.Context, decisionMaker *DecisionMakerPod)) *MockDecisionMakerAdapter_GetIntentMerkleRoot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *DecisionMakerPod
		if args[1] != nil {
			arg1 = args[1].(*DecisionMakerPod)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDecisionMakerAdapter_GetIntentMerkleRoot_Call) Return(s string, err error) *MockDecisionMakerAdapter_GetIntentMerkleRoot_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockDecisionMakerAdapter_GetIntentMerkleRoot_Call) RunAndReturn(run func(ctx context.Context, decisionMaker *DecisionMakerPod) (string, error)) *MockDecisionMakerAdapter_GetIntentMerkleRoot_Call {
	_c.Call.Return(run)
	return _c
}

// GetPodPIDMapping provides a mock function for the type MockDecisionMakerAdapter
func (_mock *MockDecisionMakerAdapter) GetPodPIDMapping(ctx context.Context, decisionMaker *DecisionMakerPod) (*PodPIDMappingResponse, error) {
	ret := _mock.Called(ctx, decisionMaker)

	if len(ret) == 0 {
		panic("no return value specified for GetPodPIDMapping")
	}

	var r0 *PodPIDMappingResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *DecisionMakerPod) (*PodPIDMappingResponse, error)); ok {
		return returnFunc(ctx, decisionMaker)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *DecisionMakerPod) *PodPIDMappingResponse); ok {
		r0 = returnFunc(ctx, decisionMaker)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*PodPIDMappingResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *DecisionMakerPod) error); ok {
		r1 = returnFunc(ctx, decisionMaker)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDecisionMakerAdapter_GetPodPIDMapping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPodPIDMapping'
type MockDecisionMakerAdapter_GetPodPIDMapping_Call struct {
	*mock.Call
}

// GetPodPIDMapping is a helper method to define mock.On call
//   - ctx context.Context
//   - decisionMaker *DecisionMakerPod
func (_e *MockDecisionMakerAdapter_Expecter) GetPodPIDMapping(ctx interface{}, decisionMaker interface{}) *MockDecisionMakerAdapter_GetPodPIDMapping_Call {
	return &MockDecisionMakerAdapter_GetPodPIDMapping_Call{Call: _e.mock.On("GetPodPIDMapping", ctx, decisionMaker)}
}

func (_c *MockDecisionMakerAdapter_GetPodPIDMapping_Call) Run(run func(ctx context.Context, decisionMaker *DecisionMakerPod)) *MockDecisionMakerAdapter_GetPodPIDMapping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *DecisionMakerPod
		if args[1] != nil {
			arg1 = args[1].(*DecisionMakerPod)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDecisionMakerAdapter_GetPodPIDMapping_Call) Return(podPIDMappingResponse *PodPIDMappingResponse, err error) *MockDecisionMakerAdapter_GetPodPIDMapping_Call {
	_c.Call.Return(podPIDMappingResponse, err)
	return _c
}

func (_c *MockDecisionMakerAdapter_GetPodPIDMapping_Call) RunAndReturn(run func(ctx context.Context, decisionMaker *DecisionMakerPod) (*PodPIDMappingResponse, error)) *MockDecisionMakerAdapter_GetPodPIDMapping_Call {
	_c.Call.Return(run)
	return _c
}

// SendSchedulingIntent provides a mock function for the type MockDecisionMakerAdapter
func (_mock *MockDecisionMakerAdapter) SendSchedulingIntent(ctx context.Context, decisionMaker *DecisionMakerPod, intents []*ScheduleIntent) error {
	ret := _mock.Called(ctx, decisionMaker, intents)

	if len(ret) == 0 {
		panic("no return value specified for SendSchedulingIntent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *DecisionMakerPod, []*ScheduleIntent) error); ok {
		r0 = returnFunc(ctx, decisionMaker, intents)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDecisionMakerAdapter_SendSchedulingIntent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendSchedulingIntent'
type MockDecisionMakerAdapter_SendSchedulingIntent_Call struct {
	*mock.Call
}

// SendSchedulingIntent is a helper method to define mock.On call
//   - ctx context.Context
//   - decisionMaker *DecisionMakerPod
//   - intents []*ScheduleIntent
func (_e *MockDecisionMakerAdapter_Expecter) SendSchedulingIntent(ctx interface{}, decisionMaker interface{}, intents interface{}) *MockDecisionMakerAdapter_SendSchedulingIntent_Call {
	return &MockDecisionMakerAdapter_SendSchedulingIntent_Call{Call: _e.mock.On("SendSchedulingIntent", ctx, decisionMaker, intents)}
}

func (_c *MockDecisionMakerAdapter_SendSchedulingIntent_Call) Run(run func(ctx context.Context, decisionMaker *DecisionMakerPod, intents []*ScheduleIntent)) *MockDecisionMakerAdapter_SendSchedulingIntent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *DecisionMakerPod
		if args[1] != nil {
			arg1 = args[1].(*DecisionMakerPod)
		}
		var arg2 []*ScheduleIntent
		if args[2] != nil {
			arg2 = args[2].([]*ScheduleIntent)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDecisionMakerAdapter_SendSchedulingIntent_Call) Return(err error) *MockDecisionMakerAdapter_SendSchedulingIntent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDecisionMakerAdapter_SendSchedulingIntent_Call) RunAndReturn(run func(ctx context.Context, decisionMaker *DecisionMakerPod, intents []*ScheduleIntent) error) *MockDecisionMakerAdapter_SendSchedulingIntent_Call {
	_c.Call.Return(run)
	return _c
}
